name: dises
channels:
  - conda-forge
dependencies:
  - python=3.11 
  - pip

  # Core scientific stack
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - seaborn
  - matplotlib
  - contextily
  - openpyxl

  # Geospatial stack
  - proj 
  - proj-data
  - gdal
  - fiona
  - shapely
  - rasterio
  - geopandas
  - pyproj
  - scikit-gstat
  - pysal
  - libpysal
  - esda
  - spreg

  # Pip installs
  - pip:
      - PyPDF2

